#!/usr/bin/env bash

ARGS="$@"
REGION=$4
IFS='=' read -ra REG <<< "$REGION"
ORIGCONFIG=`basename -s .json "${@: -1}"`
NEWCONFIG="$ORIGCONFIG-${REG[1]}.json"
ARGS="${ARGS/$ORIGCONFIG.json/$NEWCONFIG}"

/opt/packer $ARGS

